export const MESSAGE_TYPES = Object.freeze({
  GET_SETTINGS: "getSettings",
  SAVE_SETTINGS: "saveSettings",
  SEARCH_ADS: "searchAds",
  EXPORT_BIBTEX: "exportBibtex",
  RESOLVE_BIB_TARGET: "resolveBibTarget",
  APPLY_INSERTION: "applyInsertion"
});

export const DEFAULT_SETTINGS = Object.freeze({
  adsApiToken: "",
  sourceProfile: "astrophysics",
  primarySource: "ads",
  fallbackSources: [],
  sourceApiTokens: {},
  defaultProjectBibFileOverride: {},
  contextWindowChars: 500,
  shortcutHelpText: "Alt+Shift+E",
  themeMode: "auto",
  returnToSourceAfterInsert: false,
  citationKeyMode: "authoryear",
  bibliographyInsertMode: "append",
  defaultSearchMode: "contextual"
});

export const TITLE_STOPWORDS = new Set([
  "a",
  "an",
  "and",
  "as",
  "at",
  "by",
  "for",
  "from",
  "in",
  "into",
  "of",
  "on",
  "or",
  "the",
  "to",
  "using",
  "with",
  "without"
]);

export const CONTEXT_STOPWORDS = new Set([
  ...TITLE_STOPWORDS,
  "are",
  "be",
  "been",
  "can",
  "could",
  "census",
  "did",
  "do",
  "does",
  "et",
  "appear",
  "appeared",
  "appears",
  "find",
  "given",
  "have",
  "here",
  "however",
  "important",
  "kill",
  "killed",
  "may",
  "near",
  "new",
  "our",
  "paper",
  "people",
  "recent",
  "result",
  "results",
  "show",
  "shows",
  "study",
  "studies",
  "studied",
  "studying",
  "that",
  "their",
  "they",
  "these",
  "this",
  "those",
  "there",
  "via",
  "was",
  "were",
  "which",
  "who",
  "work",
  "works",
  "found",
  "other",
  "others",
  "also",
  "publication",
  "publications",
  "target",
  "targets"
]);
